{% set name = "flake8-print" %}
{% set version = "3.0.1" %}
{% set sha256 = "255b01f0932f65fb8ce70a65f0f2abb4a05faf25f9fe53275cd13cacdc0179f5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - flake8 >=1.5
    - pycodestyle
    - six

test:
  commands:
    - "flake8 --version | grep flake8-print:"

about:
  home: https://github.com/jbkahn/flake8-print
  license: MIT
  license_family: MIT
  summary: 'Flake8 plugin to check for print statements in python files.'
  dev_url: https://github.com/jbkahn/flake8-print

extra:
  recipe-maintainers:
    - dopplershift
