travis:
  secure:
    BINSTAR_TOKEN: Sh/AbYk4FfSn3lQcnZ6CxFU26Vd8OTEXu6ce+KbYA72Zz+oQFu492ZdgUsMyd9uJfhtL73G5l5tB9Uty/ux7Bdoasz8YLQsXPlJlZURqyYzkwvxB3vjdy0uA0jqx36+lcqiBPq2IJ5HsjOejvwI7gcy2vAPt5/QUm+HETO1e6EU9GYcKHIwU0YakAS2uBaWKLjgVCdjsvjSSpfeS0U8jJpmAPz42/2FcyD+xPzIn4wymlnyQ2Fkmgh5T1IFtB0+/C4M2agJKCUZDIaZix1YsQmZY5pR9vbE1vVfXJMnwHODzwKn5epTqrocxIeWSl99El6769Zv4YTSM2ccEG9kCVMXAVI/Ttx9HvdYYjvwyTSNU4OztdNdz3HFcYoRr6wN1UyzEnFYFgd+1Jpuf5fmaW98Utyv6Bf1i58vsNzxsQ+lB0p1V5nZq5lzq2RW05N9+3ddic18S4sNIGZ9ADa1mTOvofsd9bcIsz577GinUj6OAtrAhFZqngWV64D/JQLkGwgUJUEoz9swItvXO2zwlvFTq0/Ndqpw6xb8tF2+dTeW0fXdMRtTA/N9Jobmb585WKDHxjYNGmiDBLs5+d5vmVkONAV3SfBiLwjcOtIWH6/PbCbujdoJL94uNkQcGOr4giQ7+akUkrOVMNrZ0BcpDi1P/r6oqj/u0JCqFsHEhoQg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
