travis:
  secure:
    BINSTAR_TOKEN: cWOVTeeNIesDenyZfJPqgPRBHoxreuRmDQTb/KEma5e+1srCozdS5reSNh9gbGtUtwX5+37ItA63blCCBAHfeXpziw7MfsoBDj6FIUd9hSL5NrqoJMdTVaPwGQAuk6xdjQmCCSX0wG/Yi2hKWvPJwF0wuTuSU07k3NhIIxcIDpv6CRsPDjPHmbx68NxFmisyBs7BGcfEHWTuASZ5nL+9/lz1Y2DoeB3HYdMVaMeViTagquQvJSsvOwOs0pEn1lAzCba+WduXiaLr1myzBabgQOpQK+xoFfTCxih0JYyA45HreqnEI9drVvxW8Tm2ZA80EEfgW9KrCk1QQzdXLcek5Ce9gWfR2XbzjEKks+VSv9zlSsbeiD34zNTFghUfhZtJQBkgfBNz29a5CgqCPe4lo9iRXwDybFprCj5Rq4dPc6y8FPb7Q8TgG26au3+Zgk5CcjeBtVR7VX/PjHBDQMcQwCFt4AW+2v2TyO9Xv3Trq+XFjC6YM9LA7i6panU+vzGrcOcMq4b7ZiFY6D3ivn62lVZ6Qw7Qo73WvqudNViujr43P2eaHlRIr9kbykry5VS9UuisHZh9W2Xwq3u5SwZy3YTX5YR56kJiV3Zr49C9KWOo6dw+Q2Qm1zEmUAujC4WSJi+JRWVchdXX8TDuQZNg4kgSfKaFRYkvORvRnOtSbAs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
