travis:
  secure:
    BINSTAR_TOKEN: bQstYb/GspktRFeB1sM9QIu7FsDWCRvhJ0OJIccPuh2l/km3NvYkIYpykq5G2282voLNA6C8onsuSKRrfqqcXqx+gXStifLr7XbvB/EQqB3tARloCNdeDUQx2M1tvtwwu2jZEonXQ667bJ32/YWpZlMz5fHQlz8rqJGtQ7Z6I9QTsLVLUbby6F10LycWBCJvd9IZ4+iPCiL9lytVZN00tGu06ydg+WOyH4UXKfa3ZvNsAZnKf2eE3hkMWVvwdLxo/vs+wLmEEgr8uOpgBszG20a6VBqWZx/EwY+ZH4vBw/ZyNHWHrdMKf+F5D9eEWrOTAd9r27hocY/j/zo1yQxPoAo6Ppr5E/h24Qxc/Z7DttWDRv+pTxwahggAddYlsACsR+cunv8fnntF051ZuY20qoTRk0SlrzBcAF6IipNekliTyj2TBkjwsFxygAggCbSY/nf79gCtH8w1mIuK8MtoMaWdRQ6ylf4nCjTWnHH8+FOZ4sMNhnkXIkIyYRv4VVqmk/7O4Ark2GRGjLwxh2tbmtDYjq4fRBP+xRhc271NWnSOWHhJ3I9REoqSzMs7mmNE6+6oJdTWGhHFzB57Hq7m7ZmhWehrtTUvmwVEn1hvDMkOpEkWyFpWxYSznZ+bbIsHTfxkrJUO0G6DZ2V7K1H1Dyu6snBapeLd6kqc8Kx7DRA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
